# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 11 * * *"
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os : ["ubuntu-latest", "macos-latest"]                
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        activate-environment: fermipy
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: gtirfs
      shell: bash -l {0}
      run: |
        gtirfs
    - name: test_eblAtten
      shell: bash -l {0}
      run: |
        test_eblAtten
    - name: gtebl
      shell: bash -l {0}
      run: |
        gtebl 1 0.1 test.csv

